"""init

Revision ID: 01b23fbee2f9
Revises: 1cdceb9dadd2
Create Date: 2022-08-25 15:39:01.882210

"""

# revision identifiers, used by Alembic.
revision = '01b23fbee2f9'
down_revision = '1cdceb9dadd2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
