"""init

Revision ID: 01e9ab785b22
Revises: 177cea0c1d36
Create Date: 2022-08-25 18:17:19.778995

"""

# revision identifiers, used by Alembic.
revision = '01e9ab785b22'
down_revision = '177cea0c1d36'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
