"""init

Revision ID: 096e27ead16d
Revises: fb74b3bf4dd4
Create Date: 2022-08-25 16:51:31.259907

"""

# revision identifiers, used by Alembic.
revision = '096e27ead16d'
down_revision = 'fb74b3bf4dd4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
