"""init

Revision ID: 0bb3f02fa4dc
Revises: a93bcf36e1a0
Create Date: 2022-08-25 17:04:54.232715

"""

# revision identifiers, used by Alembic.
revision = '0bb3f02fa4dc'
down_revision = 'a93bcf36e1a0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
