"""init

Revision ID: 0e2d521b53d3
Revises: 4a9397be6be2
Create Date: 2022-08-25 09:43:06.618294

"""

# revision identifiers, used by Alembic.
revision = '0e2d521b53d3'
down_revision = '4a9397be6be2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
