"""init

Revision ID: 147bd620c35a
Revises: e29bb4938adf
Create Date: 2022-08-25 10:20:49.811965

"""

# revision identifiers, used by Alembic.
revision = '147bd620c35a'
down_revision = 'e29bb4938adf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
