"""init

Revision ID: 177cea0c1d36
Revises: db33f5bf5121
Create Date: 2022-08-25 18:15:55.131491

"""

# revision identifiers, used by Alembic.
revision = '177cea0c1d36'
down_revision = 'db33f5bf5121'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
