"""init

Revision ID: 181f0044bb8a
Revises: b64b493735c0
Create Date: 2022-08-25 17:42:10.214481

"""

# revision identifiers, used by Alembic.
revision = '181f0044bb8a'
down_revision = 'b64b493735c0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
