"""init

Revision ID: 1873cc7b35f4
Revises: da107d4fb5d1
Create Date: 2022-08-25 17:06:29.438601

"""

# revision identifiers, used by Alembic.
revision = '1873cc7b35f4'
down_revision = 'da107d4fb5d1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
