"""init

Revision ID: 1940cef839ce
Revises: 438f13406c10
Create Date: 2022-08-25 10:22:44.716356

"""

# revision identifiers, used by Alembic.
revision = '1940cef839ce'
down_revision = '438f13406c10'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
