"""init

Revision ID: 1cdceb9dadd2
Revises: 21927c2f2690
Create Date: 2022-08-25 15:34:49.308511

"""

# revision identifiers, used by Alembic.
revision = '1cdceb9dadd2'
down_revision = '21927c2f2690'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
