"""init

Revision ID: 21927c2f2690
Revises: a57618ba1d74
Create Date: 2022-08-25 13:15:04.722343

"""

# revision identifiers, used by Alembic.
revision = '21927c2f2690'
down_revision = 'a57618ba1d74'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
