"""init

Revision ID: 23a350fbe6d2
Revises: 51bcae79d710
Create Date: 2022-08-25 16:37:33.852438

"""

# revision identifiers, used by Alembic.
revision = '23a350fbe6d2'
down_revision = '51bcae79d710'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
