"""init

Revision ID: 25a372feaa44
Revises: cc59053d7583
Create Date: 2022-08-25 16:48:59.808923

"""

# revision identifiers, used by Alembic.
revision = '25a372feaa44'
down_revision = 'cc59053d7583'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
