"""init

Revision ID: 25ce520193cb
Revises: dd33cb03d01f
Create Date: 2022-08-25 09:40:59.387598

"""

# revision identifiers, used by Alembic.
revision = '25ce520193cb'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
