"""init

Revision ID: 2cf048fab2c8
Revises: 315986cf30b3
Create Date: 2022-08-25 16:44:04.445035

"""

# revision identifiers, used by Alembic.
revision = '2cf048fab2c8'
down_revision = '315986cf30b3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
