"""init

Revision ID: 30a01956c92f
Revises: fc911180ad24
Create Date: 2022-08-25 09:53:09.701428

"""

# revision identifiers, used by Alembic.
revision = '30a01956c92f'
down_revision = 'fc911180ad24'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
