"""init

Revision ID: 315986cf30b3
Revises: 23a350fbe6d2
Create Date: 2022-08-25 16:41:55.953257

"""

# revision identifiers, used by Alembic.
revision = '315986cf30b3'
down_revision = '23a350fbe6d2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
