"""init

Revision ID: 3c8bc1eb6c32
Revises: 9bb2922a861e
Create Date: 2022-08-25 16:32:58.285434

"""

# revision identifiers, used by Alembic.
revision = '3c8bc1eb6c32'
down_revision = '9bb2922a861e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
