"""init

Revision ID: 438f13406c10
Revises: 147bd620c35a
Create Date: 2022-08-25 10:21:37.453157

"""

# revision identifiers, used by Alembic.
revision = '438f13406c10'
down_revision = '147bd620c35a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
