"""init

Revision ID: 4a9397be6be2
Revises: 25ce520193cb
Create Date: 2022-08-25 09:41:44.017672

"""

# revision identifiers, used by Alembic.
revision = '4a9397be6be2'
down_revision = '25ce520193cb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
