"""init

Revision ID: 51bcae79d710
Revises: 3c8bc1eb6c32
Create Date: 2022-08-25 16:34:00.732327

"""

# revision identifiers, used by Alembic.
revision = '51bcae79d710'
down_revision = '3c8bc1eb6c32'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
