"""init

Revision ID: 76ddb65000fc
Revises: 181f0044bb8a
Create Date: 2022-08-25 17:52:32.496623

"""

# revision identifiers, used by Alembic.
revision = '76ddb65000fc'
down_revision = '181f0044bb8a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
