"""init

Revision ID: 7d1dc498f50e
Revises: cee93c8019dc
Create Date: 2022-08-25 17:03:46.190723

"""

# revision identifiers, used by Alembic.
revision = '7d1dc498f50e'
down_revision = 'cee93c8019dc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
