"""init

Revision ID: 9bb2922a861e
Revises: 01b23fbee2f9
Create Date: 2022-08-25 16:31:26.690531

"""

# revision identifiers, used by Alembic.
revision = '9bb2922a861e'
down_revision = '01b23fbee2f9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
