"""init

Revision ID: a57618ba1d74
Revises: 1940cef839ce
Create Date: 2022-08-25 10:23:34.778763

"""

# revision identifiers, used by Alembic.
revision = 'a57618ba1d74'
down_revision = '1940cef839ce'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
