"""init

Revision ID: a79d01ade9a7
Revises: b445fdc3f7a2
Create Date: 2022-08-25 16:44:55.067493

"""

# revision identifiers, used by Alembic.
revision = 'a79d01ade9a7'
down_revision = 'b445fdc3f7a2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
