"""init

Revision ID: a93bcf36e1a0
Revises: 7d1dc498f50e
Create Date: 2022-08-25 17:04:06.526695

"""

# revision identifiers, used by Alembic.
revision = 'a93bcf36e1a0'
down_revision = '7d1dc498f50e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
