"""init

Revision ID: aebcc5dd9249
Revises: 1873cc7b35f4
Create Date: 2022-08-25 17:21:34.339147

"""

# revision identifiers, used by Alembic.
revision = 'aebcc5dd9249'
down_revision = '1873cc7b35f4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
