"""init

Revision ID: b445fdc3f7a2
Revises: 2cf048fab2c8
Create Date: 2022-08-25 16:44:24.141887

"""

# revision identifiers, used by Alembic.
revision = 'b445fdc3f7a2'
down_revision = '2cf048fab2c8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
