"""init

Revision ID: b64b493735c0
Revises: aebcc5dd9249
Create Date: 2022-08-25 17:29:31.033773

"""

# revision identifiers, used by Alembic.
revision = 'b64b493735c0'
down_revision = 'aebcc5dd9249'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
