"""init

Revision ID: c9a7079ed95c
Revises: f0a91c8df836
Create Date: 2022-08-25 17:03:16.525234

"""

# revision identifiers, used by Alembic.
revision = 'c9a7079ed95c'
down_revision = 'f0a91c8df836'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
