"""init

Revision ID: cc59053d7583
Revises: a79d01ade9a7
Create Date: 2022-08-25 16:46:11.164992

"""

# revision identifiers, used by Alembic.
revision = 'cc59053d7583'
down_revision = 'a79d01ade9a7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
