"""init

Revision ID: cee93c8019dc
Revises: c9a7079ed95c
Create Date: 2022-08-25 17:03:27.406580

"""

# revision identifiers, used by Alembic.
revision = 'cee93c8019dc'
down_revision = 'c9a7079ed95c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
