"""init

Revision ID: da107d4fb5d1
Revises: 0bb3f02fa4dc
Create Date: 2022-08-25 17:06:09.914678

"""

# revision identifiers, used by Alembic.
revision = 'da107d4fb5d1'
down_revision = '0bb3f02fa4dc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
