"""init

Revision ID: db33f5bf5121
Revises: e8f7d1793c97
Create Date: 2022-08-25 18:12:13.537247

"""

# revision identifiers, used by Alembic.
revision = 'db33f5bf5121'
down_revision = 'e8f7d1793c97'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
