"""init

Revision ID: e29bb4938adf
Revises: 30a01956c92f
Create Date: 2022-08-25 10:20:22.285412

"""

# revision identifiers, used by Alembic.
revision = 'e29bb4938adf'
down_revision = '30a01956c92f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
