"""init

Revision ID: e8f7d1793c97
Revises: fafa251ca782
Create Date: 2022-08-25 18:06:02.672646

"""

# revision identifiers, used by Alembic.
revision = 'e8f7d1793c97'
down_revision = 'fafa251ca782'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
