"""init

Revision ID: f0a91c8df836
Revises: 096e27ead16d
Create Date: 2022-08-25 16:51:56.492847

"""

# revision identifiers, used by Alembic.
revision = 'f0a91c8df836'
down_revision = '096e27ead16d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
