"""init

Revision ID: f5dd49750c11
Revises: 25a372feaa44
Create Date: 2022-08-25 16:50:08.985575

"""

# revision identifiers, used by Alembic.
revision = 'f5dd49750c11'
down_revision = '25a372feaa44'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
