"""init

Revision ID: fafa251ca782
Revises: 76ddb65000fc
Create Date: 2022-08-25 18:05:47.521171

"""

# revision identifiers, used by Alembic.
revision = 'fafa251ca782'
down_revision = '76ddb65000fc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
