"""init

Revision ID: fb74b3bf4dd4
Revises: f5dd49750c11
Create Date: 2022-08-25 16:50:55.672245

"""

# revision identifiers, used by Alembic.
revision = 'fb74b3bf4dd4'
down_revision = 'f5dd49750c11'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
