"""init

Revision ID: fc911180ad24
Revises: 0e2d521b53d3
Create Date: 2022-08-25 09:44:37.345491

"""

# revision identifiers, used by Alembic.
revision = 'fc911180ad24'
down_revision = '0e2d521b53d3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
